import uuid
from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class GuidanceLevel(str, Enum):
    FULL = "FULL"
    MODERATE = "MODERATE"
    MINIMAL = "MINIMAL"
    REJECTED = "REJECTED"


class ViolationType(str, Enum):
    DIRECT_SOLUTION_REQUEST = "DIRECT_SOLUTION_REQUEST"
    ANSWER_FARMING = "ANSWER_FARMING"
    FREQ_LIMIT_EXCEEDED = "FREQ_LIMIT_EXCEEDED"


class ViolationSeverity(str, Enum):
    MAJOR = "MAJOR"
    MINOR = "MINOR"


class QuestionClassification(str, Enum):
    CONCEPTUAL = "CONCEPTUAL"         # student seeks understanding of a concept
    PROCEDURAL = "PROCEDURAL"         # student asks how to approach a problem type
    CLARIFICATION = "CLARIFICATION"   # student asks about lab instructions/wording
    DIRECT_SOLUTION = "DIRECT_SOLUTION"  # student requests the specific answer/code
    ANSWER_FARMING = "ANSWER_FARMING"    # incremental pattern assembling full solution


class SessionStatus(str, Enum):
    ACTIVE = "active"
    CLOSED = "closed"


class ReportType(str, Enum):
    SESSION = "SESSION"
    POST_LAB = "POST_LAB"


class FinalStatus(str, Enum):
    CLEAN = "CLEAN"
    WARNING = "WARNING"
    ESCALATED = "ESCALATED"


# ---------------------------------------------------------------------------
# API request / response models
# ---------------------------------------------------------------------------

class StartSessionRequest(BaseModel):
    student_id: str = Field(..., description="Cal Poly username")
    session_id: str = Field(..., description="UUID generated by Lab Companion")
    lab_id: str = Field(..., description="Lab assignment identifier, e.g. 'lab3'")
    course_id: str = Field(default="CSC580")


class StartSessionResponse(BaseModel):
    session_id: str
    started_at: datetime
    message: str = "Session initialized."


class EndSessionRequest(BaseModel):
    student_id: str
    session_id: str


class EndSessionResponse(BaseModel):
    session_id: str
    report_id: str
    ended_at: datetime
    summary: dict


class ValidateQuestionRequest(BaseModel):
    student_id: str = Field(..., description="Cal Poly username")
    session_id: str = Field(..., description="Session UUID")
    lab_id: str = Field(..., description="Lab assignment identifier")
    course_id: str = Field(default="CSC580")
    question_text: str = Field(..., min_length=1, max_length=4000)
    conversation_history: list[dict] = Field(
        default_factory=list,
        description="Recent turns: [{'role': 'user'|'assistant', 'content': str}]",
    )


class ValidateQuestionResponse(BaseModel):
    approved: bool
    guidance_level: GuidanceLevel
    student_message: Optional[str] = None
    violation_detected: bool = False
    violation_type: Optional[ViolationType] = None
    violation_count: int = 0
    question_count: int = 0
    session_escalated: bool = False
    classification: QuestionClassification


class GenerateReportRequest(BaseModel):
    student_id: str
    session_id: str
    report_type: ReportType = ReportType.SESSION


class GenerateReportResponse(BaseModel):
    report_id: str
    report: dict


class PatchReportRequest(BaseModel):
    student_id: str
    instructor_notes: dict


class PostLabCheckRequest(BaseModel):
    student_id: str
    session_ids: list[str]
    lab_id: str
    course_id: str = "CSC580"


class PostLabCheckResponse(BaseModel):
    report_id: str
    over_reliance_indicators: dict
    summary: str


# ---------------------------------------------------------------------------
# Cosmos DB document models
# ---------------------------------------------------------------------------

class QuestionRecord(BaseModel):
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sequence_number: int
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z"
    )
    text: str
    classification: QuestionClassification
    guidance_level: GuidanceLevel
    violation: bool
    violation_type: Optional[ViolationType] = None
    student_message_sent: Optional[str] = None


class ViolationRecord(BaseModel):
    violation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question_id: str
    sequence_number: int
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat() + "Z"
    )
    violation_type: ViolationType
    severity: ViolationSeverity
    question_text: str
    guidance_level: GuidanceLevel
    student_message_sent: str


class SessionDocument(BaseModel):
    id: str                                        # = session_id (Cosmos document id)
    student_id: str                                # partition key
    session_id: str
    lab_id: str
    course_id: str
    started_at: str
    ended_at: Optional[str] = None
    question_count: int = 0
    violation_count: int = 0
    warning_issued: bool = False
    escalated: bool = False
    status: SessionStatus = SessionStatus.ACTIVE
    questions: list[QuestionRecord] = Field(default_factory=list)
    violations: list[ViolationRecord] = Field(default_factory=list)
    report_generated: bool = False
    report_id: Optional[str] = None
